on:
  push:
    branches:
      - master
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy file to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
          username: ${{ secrets.username }}
          server: ${{ secrets.host }}
          port: ${{ secrets.port }}
          local_path: './polecamman-frontend/build/*'
          remote_path: '/home/polecamman/public_html/'
          sftp_only: true
          password: ${{ secrets.sshkey }}
